/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iknowu_PredictionEngine_AdvanceLetterInfo */

#ifndef _Included_com_iknowu_PredictionEngine_AdvanceLetterInfo
#define _Included_com_iknowu_PredictionEngine_AdvanceLetterInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
