/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iknowu_PredictionEngine_NextWordsInfo */

#ifndef _Included_com_iknowu_PredictionEngine_NextWordsInfo
#define _Included_com_iknowu_PredictionEngine_NextWordsInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
