/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iknowu_PredictionEngine */

#ifndef _Included_com_iknowu_PredictionEngine
#define _Included_com_iknowu_PredictionEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iknowu_PredictionEngine
 * Method:    ntvNextLetters
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iknowu_PredictionEngine_ntvNextLetters
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_keyboard_PredictionEngine
 * Method:    ntvAdvanceLetter
 * Signature: (CLcom/iknowu/PredictionEngine/AdvanceLetterInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iknowu_PredictionEngine_ntvAdvanceLetter
  (JNIEnv *, jobject, jchar, jobject);

/*
 * Class:     com_keyboard_PredictionEngine
 * Method:    ntvNextWords
 * Signature: (Lcom/iknowu/PredictionEngine/NextWordsInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_iknowu_PredictionEngine_ntvNextWords
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_keyboard_PredictionEngine
 * Method:    ntvAdvanceWord
 * Signature: (Ljava/lang/String;Lcom/iknowu/PredictionEngine/AdvanceWordInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iknowu_PredictionEngine_ntvAdvanceWord
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
